Desvelted
CursedCreationsTeam/cursedcreationsteam.github.io pull request #23
Opened 2023-11-23 18:18 UTC by 4194304

functions pretty much the exact same, code needs to be cleaned up though

2023-11-24 16:32 UTC, SolDev69 commented
Will not merge.

2023-12-15 01:20 UTC, SolDev69 commented
This the right pr? I'll review this tomorrow

2023-12-16 04:30 UTC, 4194304 commented
everything is set up so no problems on that part

2023-12-17 05:27 UTC, 4194304 commented
Repository is up to date now

2023-12-17 17:03 UTC, SolDev69 requested changes
You just ripped a bunch of stuff from inspect element 🤦‍♂️

2023-12-17 17:03 UTC, SolDev69 commented on css/stylesheet0.css
half of these are ripped from svelte

2023-12-17 17:03 UTC, SolDev69 commented on css/stylesheet8.css
Ripped from svelte

2023-12-17 17:03 UTC, SolDev69 commented on css/stylesheet9.css
ripped from svelte

2023-12-17 21:29 UTC, 4194304 commented on css/stylesheet0.css
I know that

2023-12-17 21:30 UTC, 4194304 commented on css/stylesheet9.css
I can merge the stylesheets

2023-12-18 05:51 UTC, 4194304 commented
Cleaned up code

2024-01-16 23:22 UTC, closed without merging